import 'server-only';

import ExcelJS from 'exceljs';

import { prisma } from '@/lib/db';
import type { SessionUser } from '@/lib/auth/session';
import { branchScope, findingScope } from '@/lib/auth/guard';
import { branchPerformance } from '@/lib/analytics';
import { orgConfig } from '@/lib/domain/settings';
import { deadlineState, describeRemaining, escalationLabel } from '@/lib/domain/deadlines';
import { FINDING_STATUS_LABELS } from '@/lib/domain/findings';
import { SEVERITY_LABEL } from '@/lib/format';

const HEADER_FILL = 'FF154A91';

type Column = { header: string; key: string; width: number };

function sheet(workbook: ExcelJS.Workbook, name: string, columns: Column[]) {
  const ws = workbook.addWorksheet(name, {
    views: [{ state: 'frozen', ySplit: 1 }],
  });
  ws.columns = columns;

  const header = ws.getRow(1);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_FILL } };
  header.alignment = { vertical: 'middle' };
  header.height = 22;

  ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };
  return ws;
}

function meta(workbook: ExcelJS.Workbook, user: SessionUser, title: string, notes: string[]) {
  const ws = workbook.addWorksheet('About', { views: [{ showGridLines: false }] });
  ws.columns = [{ width: 26 }, { width: 90 }];
  ws.addRow([title]).font = { bold: true, size: 14 };
  ws.addRow([]);
  ws.addRow(['Organization', user.organizationName]);
  ws.addRow(['Generated by', `${user.name} (${user.email})`]);
  ws.addRow(['Generated at', new Date().toISOString()]);
  ws.addRow(['Scope', 'Only branches this user is permitted to see are included.']);
  ws.addRow([]);
  for (const note of notes) ws.addRow(['', note]);
  ws.getColumn(1).font = { bold: true, size: 10 };
  return ws;
}

async function toBuffer(workbook: ExcelJS.Workbook) {
  const data = await workbook.xlsx.writeBuffer();
  return Buffer.from(data);
}

// ---------------------------------------------------------------------------

/** Every finding in scope, with its accountability chain. */
export async function findingsWorkbook(
  user: SessionUser,
  filters: { status?: string; severity?: string; branchId?: string; from?: Date; to?: Date } = {},
) {
  const cfg = await orgConfig(user.organizationId);
  const scope = await findingScope(user);
  const now = new Date();

  const findings = await prisma.finding.findMany({
    where: {
      ...scope,
      ...(filters.branchId ? { branchId: filters.branchId } : {}),
      ...(filters.severity ? { severity: filters.severity as never } : {}),
      ...(filters.status === 'open'
        ? { status: { notIn: ['CLOSED', 'CANCELLED'] } }
        : filters.status
          ? { status: filters.status as never }
          : {}),
      ...(filters.from || filters.to
        ? {
            createdAt: {
              ...(filters.from ? { gte: filters.from } : {}),
              ...(filters.to ? { lte: filters.to } : {}),
            },
          }
        : {}),
    },
    orderBy: [{ severity: 'asc' }, { dueDate: 'asc' }],
    include: {
      branch: { select: { name: true, code: true, city: true, region: { select: { name: true } } } },
      assignedTo: { select: { name: true, email: true } },
      createdBy: { select: { name: true } },
      closedBy: { select: { name: true } },
      inspection: { select: { reference: true } },
      _count: { select: { evidence: true, correctiveActions: true } },
    },
  });

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BranchCheck';
  workbook.created = new Date();

  meta(workbook, user, 'Findings export', [
    'One row per finding. "Deadline state" is computed at export time.',
    'Rejections counts how many times submitted evidence was sent back for rework.',
    'A finding is only Closed once a verifier accepted evidence of the correction.',
  ]);

  const ws = sheet(workbook, 'Findings', [
    { header: 'Finding', key: 'number', width: 16 },
    { header: 'Region', key: 'region', width: 18 },
    { header: 'Branch', key: 'branch', width: 24 },
    { header: 'Branch code', key: 'code', width: 12 },
    { header: 'Category', key: 'category', width: 18 },
    { header: 'Checklist item', key: 'item', width: 32 },
    { header: 'Observation', key: 'observation', width: 60 },
    { header: 'Severity', key: 'severity', width: 11 },
    { header: 'Status', key: 'status', width: 20 },
    { header: 'Responsible person', key: 'owner', width: 22 },
    { header: 'Owner email', key: 'ownerEmail', width: 30 },
    { header: 'Raised by', key: 'raisedBy', width: 20 },
    { header: 'Raised on', key: 'createdAt', width: 13 },
    { header: 'Due date', key: 'dueDate', width: 13 },
    { header: 'Deadline state', key: 'deadline', width: 14 },
    { header: 'Time remaining', key: 'remaining', width: 16 },
    { header: 'Escalated to', key: 'escalation', width: 20 },
    { header: 'Recurring', key: 'recurring', width: 11 },
    { header: 'Occurrences', key: 'occurrences', width: 12 },
    { header: 'Rejections', key: 'rejections', width: 11 },
    { header: 'Evidence files', key: 'evidence', width: 14 },
    { header: 'Closed on', key: 'closedAt', width: 13 },
    { header: 'Closed by', key: 'closedBy', width: 20 },
    { header: 'Source inspection', key: 'inspection', width: 18 },
  ]);

  for (const f of findings) {
    const state = deadlineState(f, cfg.dueSoonHours, now);
    const row = ws.addRow({
      number: f.number,
      region: f.branch.region.name,
      branch: f.branch.name,
      code: f.branch.code,
      category: f.categoryName,
      item: f.itemText,
      observation: f.observation,
      severity: SEVERITY_LABEL[f.severity],
      status: FINDING_STATUS_LABELS[f.status],
      owner: f.assignedTo?.name ?? 'Unassigned',
      ownerEmail: f.assignedTo?.email ?? '',
      raisedBy: f.createdBy.name,
      createdAt: f.createdAt,
      dueDate: f.dueDate,
      deadline: state === 'ON_TRACK' ? 'On Track' : state === 'DUE_SOON' ? 'Due Soon' : state === 'OVERDUE' ? 'Overdue' : 'Closed',
      remaining: describeRemaining(f.dueDate, f.status, now),
      escalation: escalationLabel(f.escalationLevel),
      recurring: f.isRecurring ? 'Yes' : 'No',
      occurrences: f.recurrenceCount,
      rejections: f.rejectionCount,
      evidence: f._count.evidence,
      closedAt: f.closedAt ?? '',
      closedBy: f.closedBy?.name ?? '',
      inspection: f.inspection?.reference ?? '',
    });

    row.getCell('createdAt').numFmt = 'dd mmm yyyy';
    row.getCell('dueDate').numFmt = 'dd mmm yyyy';
    if (f.closedAt) row.getCell('closedAt').numFmt = 'dd mmm yyyy';

    // Colour only what carries meaning: severity and an overdue deadline.
    const sevColor =
      f.severity === 'CRITICAL' ? 'FF91183E' : f.severity === 'HIGH' ? 'FFBE2C2C' : f.severity === 'MEDIUM' ? 'FFB47908' : 'FF5A6474';
    row.getCell('severity').font = { color: { argb: sevColor }, bold: f.severity === 'CRITICAL' };
    if (state === 'OVERDUE') {
      row.getCell('deadline').font = { color: { argb: 'FFBE2C2C' }, bold: true };
    }
    if (f.isRecurring) row.getCell('recurring').font = { color: { argb: 'FF91183E' }, bold: true };
  }

  return { buffer: await toBuffer(workbook), count: findings.length };
}

/** Branch scorecard: latest score, movement and open workload. */
export async function branchPerformanceWorkbook(user: SessionUser) {
  const scope = await branchScope(user);
  const branches = await prisma.branch.findMany({
    where: scope,
    select: { id: true, status: true, branchType: true, city: true, cluster: { select: { name: true } } },
  });
  const perf = await branchPerformance(user, branches.map((b) => b.id));
  const extra = new Map(branches.map((b) => [b.id, b]));

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BranchCheck';

  meta(workbook, user, 'Branch performance export', [
    '"Change" is the latest score minus the previous inspection score.',
    '"Closure rate" is closed findings as a share of all findings ever raised at the branch.',
  ]);

  const ws = sheet(workbook, 'Branch performance', [
    { header: 'Branch', key: 'name', width: 26 },
    { header: 'Code', key: 'code', width: 12 },
    { header: 'Region', key: 'region', width: 18 },
    { header: 'Cluster', key: 'cluster', width: 20 },
    { header: 'City', key: 'city', width: 16 },
    { header: 'Type', key: 'type', width: 20 },
    { header: 'Status', key: 'status', width: 11 },
    { header: 'Latest score', key: 'latest', width: 13 },
    { header: 'Previous score', key: 'previous', width: 14 },
    { header: 'Change', key: 'change', width: 10 },
    { header: 'Inspections', key: 'inspections', width: 12 },
    { header: 'Open findings', key: 'open', width: 14 },
    { header: 'Overdue', key: 'overdue', width: 11 },
    { header: 'Critical open', key: 'critical', width: 13 },
    { header: 'Closure rate %', key: 'closure', width: 14 },
  ]);

  for (const p of [...perf].sort((a, b) => (b.latestScore ?? -1) - (a.latestScore ?? -1))) {
    const b = extra.get(p.branchId);
    const change =
      p.latestScore !== null && p.previousScore !== null
        ? Math.round((p.latestScore - p.previousScore) * 10) / 10
        : null;

    const row = ws.addRow({
      name: p.name,
      code: p.code,
      region: p.regionName,
      cluster: b?.cluster?.name ?? '',
      city: p.city,
      type: b?.branchType ?? '',
      status: b?.status === 'ACTIVE' ? 'Active' : 'Inactive',
      latest: p.latestScore,
      previous: p.previousScore,
      change,
      inspections: p.inspections,
      open: p.openFindings,
      overdue: p.overdueFindings,
      critical: p.criticalFindings,
      closure: p.closureRate === null ? null : Math.round(p.closureRate * 10) / 10,
    });

    row.getCell('latest').numFmt = '0.0';
    row.getCell('previous').numFmt = '0.0';
    row.getCell('change').numFmt = '+0.0;-0.0;0.0';
    row.getCell('closure').numFmt = '0.0';

    if (change !== null) {
      row.getCell('change').font = { color: { argb: change >= 0 ? 'FF15803D' : 'FFBE2C2C' } };
    }
    if (p.overdueFindings > 0) row.getCell('overdue').font = { color: { argb: 'FFBE2C2C' }, bold: true };
    if (p.criticalFindings > 0) row.getCell('critical').font = { color: { argb: 'FF91183E' }, bold: true };
  }

  return { buffer: await toBuffer(workbook), count: perf.length };
}

/** Corrective action report: every remediation attempt and its verdict. */
export async function correctiveActionWorkbook(user: SessionUser) {
  const scope = await findingScope(user);

  const actions = await prisma.correctiveAction.findMany({
    where: { finding: scope },
    orderBy: [{ finding: { number: 'asc' } }, { attempt: 'asc' }],
    include: {
      finding: {
        select: {
          number: true,
          categoryName: true,
          itemText: true,
          severity: true,
          status: true,
          dueDate: true,
          branch: { select: { name: true, code: true } },
        },
      },
      submittedBy: { select: { name: true } },
      verifiedBy: { select: { name: true } },
      _count: { select: { evidence: true } },
    },
  });

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BranchCheck';

  meta(workbook, user, 'Corrective action report', [
    'One row per remediation attempt. A finding with several rows was rejected and reworked.',
    'The verifier comment on a rejected attempt states exactly what was missing.',
  ]);

  const ws = sheet(workbook, 'Corrective actions', [
    { header: 'Finding', key: 'number', width: 16 },
    { header: 'Branch', key: 'branch', width: 24 },
    { header: 'Category', key: 'category', width: 18 },
    { header: 'Checklist item', key: 'item', width: 30 },
    { header: 'Severity', key: 'severity', width: 11 },
    { header: 'Finding status', key: 'status', width: 20 },
    { header: 'Attempt', key: 'attempt', width: 9 },
    { header: 'Action described', key: 'description', width: 60 },
    { header: 'Submitted by', key: 'submittedBy', width: 22 },
    { header: 'Submitted on', key: 'submittedAt', width: 14 },
    { header: 'Verdict', key: 'verdict', width: 12 },
    { header: 'Verified by', key: 'verifiedBy', width: 22 },
    { header: 'Verified on', key: 'verifiedAt', width: 14 },
    { header: 'Verifier comment', key: 'comment', width: 60 },
    { header: 'Evidence files', key: 'evidence', width: 14 },
  ]);

  for (const a of actions) {
    const row = ws.addRow({
      number: a.finding.number,
      branch: `${a.finding.branch.name} (${a.finding.branch.code})`,
      category: a.finding.categoryName,
      item: a.finding.itemText,
      severity: SEVERITY_LABEL[a.finding.severity],
      status: FINDING_STATUS_LABELS[a.finding.status],
      attempt: a.attempt,
      description: a.description,
      submittedBy: a.submittedBy.name,
      submittedAt: a.submittedAt,
      verdict: a.verdict === 'PENDING' ? 'Awaiting verification' : a.verdict === 'ACCEPTED' ? 'Accepted' : 'Rejected',
      verifiedBy: a.verifiedBy?.name ?? '',
      verifiedAt: a.verifiedAt ?? '',
      comment: a.verifierComment ?? '',
      evidence: a._count.evidence,
    });

    row.getCell('submittedAt').numFmt = 'dd mmm yyyy';
    if (a.verifiedAt) row.getCell('verifiedAt').numFmt = 'dd mmm yyyy';
    if (a.verdict === 'REJECTED') row.getCell('verdict').font = { color: { argb: 'FFBE2C2C' }, bold: true };
    if (a.verdict === 'ACCEPTED') row.getCell('verdict').font = { color: { argb: 'FF15803D' } };
  }

  return { buffer: await toBuffer(workbook), count: actions.length };
}
